/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FactionPickPopup.java
 *
 * Created on Oct 17, 2012, 2:03:55 PM
 */

package com.mod12.cabal.common.ui.graphics;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import com.mod12.cabal.common.util.Graphics;
import com.mod12.cabal.server.core.ServerCabal;

/**
 *
 * @author reedh
 */
public class FactionPickPopup extends javax.swing.JFrame {
	
    private DefaultListModel lineModel;
    private ServerCabal cabal;
    private int humNum;
    private int currentHum;
    private ArrayList<String> factionSet;
	
    /** Creates new form FactionPickPopup */
    public FactionPickPopup(ServerCabal cabal, int humNum) {
        this.cabal = cabal;
        this.humNum = humNum;
        currentHum = 1;
        factionSet = new ArrayList<String>();
        lineModel = new DefaultListModel();
    	initComponents();
        labelNumber.setText(Integer.toString(currentHum));
        populateList();
        Graphics.centreWindow(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPlayer = new javax.swing.JLabel();
        labelNumber = new javax.swing.JLabel();
        labelPrompt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFactions = new javax.swing.JList();
        buttonSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPlayer.setText("Player:");

        labelNumber.setText("#");

        labelPrompt.setText("please pick your faction.");

        listFactions.setModel(lineModel);
        jScrollPane1.setViewportView(listFactions);

        buttonSelect.setText("Select");
        buttonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelPlayer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPrompt))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(buttonSelect)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlayer)
                    .addComponent(labelNumber)
                    .addComponent(labelPrompt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSelect)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSelect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNumber;
    private javax.swing.JLabel labelPlayer;
    private javax.swing.JLabel labelPrompt;
    private javax.swing.JList listFactions;
    // End of variables declaration//GEN-END:variables

    private void buttonSelectActionPerformed(java.awt.event.ActionEvent evt) {
        factionSet.add((String) listFactions.getSelectedValue());
        int index = listFactions.getSelectedIndex();
        lineModel.remove(index);
        listFactions.validate();
        currentHum ++;
        if (currentHum > humNum) {
        	cabal.setHumanFaction(factionSet);        		
        	boolean result = cabal.startGame();
        	if (result == true) {
        		GameMenu gm = new GameMenu(cabal);
        		gm.enableScreens(true);
        		gm.setVisible(true);
        		this.dispose();
        	}
        	else{
        		showMessageDialog(this, "Error occured, invalid set number input, program terminating");
        		this.dispose();
        	}
        	
        }
        else{
        	labelNumber.setText(Integer.toString(currentHum));
        }
    }

    public void showMessageDialog(Component frame, String message) {
    	JOptionPane.showMessageDialog(frame, message);
    }
    
    private void populateList() {
        lineModel.clear();
        List<String> factions = cabal.getFactionNames();
        for (String name : factions) {            
                lineModel.add(lineModel.size(), name);
            }
    }

}
